name: NpcHelper
main: com.nukit.npchelper.NpcHelperPlugin
version: 1.0.0
api: ["1.0.0"]
commands:
  npchelper:
    description: Spawn or remove your NPC helper.
    usage: /npchelper
    permission: npchelper.use
permissions:
  npchelper.use:
    default: true
